RenewConfig: True  # 自动更新运行中的配置
RenewNotify: True  # 桌面通知
Overlaycontent: ""
RenewTargetKey: all # 指定使用哪一个更新
# recommand:sub.pet
content:
   all:
       - https://subscribe.cctv.rip/
   clouds:
       - https://subscribe.cctv.rip/
   kele:
       - https://subscribe.cctv.rip/
   fishport:
       - https://subscribe.cctv.rip/
   whatsup:
      - https://subscribe.cctv.rip/


